/* Part 1 — Demographic survey, language background (LEAP-Q style) and reading profile
   SurveyJS survey — edit questions here. This is the source (hand-maintained;
   NOT regenerated by tools/). */
window.IVQ = window.IVQ || {};

IVQ.parts.part1 = function (jsPsych) {
  /* ---- reusable bits -------------------------------------------------------- */
  const COUNTRIES = IVQ.lists.countries.map((c, i) => ({ value: String(i + 1), text: c }));
  const LANGS = IVQ.lists.languages.map((c) => ({ value: c, text: c })); // value = name (used in ranking)
  const YN = [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }];
  const DEAF = "{hearing_status} = 'deaf_hoh' or {native_sign} = 'yes'"; // trigger for the ASL/Deaf battery
  const AIDS_USED = "{used_hearing_aids} = 'Yes, currently' or {used_hearing_aids} = 'Yes, in the past'";
  const CI_YES = "{cochlear_implant} = 'Yes but I do not currently use it' or {cochlear_implant} = 'Yes and I currently use it'";

  const USAGE_COLS = ["All the time", "Most of the time", "Some of the time", "Rarely", "Never"]
    .map((t) => ({ value: t, text: t }));
  const SETTING_ROWS = ["Preschool/Kindergarten", "Elementary School", "Middle School", "High School", "College", "With family", "With friends"]
    .map((t) => ({ value: t, text: t }));

  const prof = (name, title) => ({
    type: "rating", name, title, rateMin: 0, rateMax: 10, displayMode: "buttons",
    minRateDescription: "No proficiency", maxRateDescription: "Native-level proficiency", isRequired: true,
  });
  const age = (name, title, extra) => Object.assign({ type: "text", name, title, inputType: "number", min: 0, max: 120, isRequired: true }, extra || {});
  const yesno = (name, title, extra) => Object.assign({ type: "radiogroup", name, title, choices: YN, isRequired: true }, extra || {});
  const info = (name, html) => ({ type: "html", name, html: `<div class="pt-info">${html}</div>` });
  const note = (name, html) => ({ type: "html", name, html: `<div class="pt-prompt">${html}</div>` });
  // "select all that apply" usage-context checkbox (shown under a proficiency item)
  const ctx = (name, title, choices) => ({
    type: "checkbox", name, title, choices,
    showOtherItem: true, otherText: "Other (please specify)",
  });
  // hours-per-week slider (used by the reading/listening/speaking/writing habit grids)
  const HOUR_LABELS = [
    { value: 0, text: "0" }, { value: 10, text: "10" }, { value: 20, text: "20" }, { value: 30, text: "30+" },
  ];
  const hours = (name, label) => ({
    type: "slider", name, title: label, sliderType: "single", min: 0, max: 30, step: 1,
    tooltipFormat: "{0} h", isRequired: true, autoGenerate: false, customLabels: HOUR_LABELS,
  });
  // a full hours-per-week page for one modality
  const habitsPage = (modality, verb, items) => ({
    name: "english_" + modality + "_habits",
    elements: [
      note("english_" + modality + "_habits_h", "In a typical week, about how many hours do you spend " + verb + "?"),
      ...items.map((label, i) => hours(modality + "_habits__row" + (i + 1), label)),
    ],
  });

  // per-language template (used for English block and each panel language)
  const languageQuestions = (suffix) => [
    prof("prof_speaking" + suffix, "Proficiency — Speaking"),
    prof("prof_understanding" + suffix, "Proficiency — Understanding spoken language"),
    prof("prof_reading" + suffix, "Proficiency — Reading"),
    prof("prof_writing" + suffix, "Proficiency — Writing"),
    age("age_start" + suffix, "At what age did you start learning it? (put 0 for from birth)"),
    age("age_read" + suffix, "At what age did you begin reading in it?"),
  ];

  const survey_json = {
    showQuestionNumbers: "off",
    showPrevButton: true,
    showProgressBar: "off",
    pageNextText: "Next",
    pagePrevText: "Previous",
    completeText: "Continue",
    pages: [
      /* ---- intro ---------------------------------------------------------- */
      { name: "experiment_instructions", elements: [info("experiment_instructions_h",
        "Welcome!<br> This experiment consists of five parts:<br> 1. A short survey about your personal information.<br> 2. Reading some sentences.<br> 3. A questionnaire about your reading experience.<br> 4. Another section of reading and answering questions.<br> 5. A questionnaire about your general inner voice experience.<br> Please read the instructions for each part carefully and answer all the questions to the best of your ability.")] },

      /* ---- basic demographics -------------------------------------------- */
      {
        name: "demographics",
        elements: [
          info("survey_instructions_h", "First Part<br> This part is a short survey about your personal information.<br> Please read the questions and answer them carefully."),
          { type: "text", name: "age", title: "How old are you?", inputType: "number", min: 18, max: 120, isRequired: true },
          {
            type: "radiogroup", name: "gender", title: "What is your gender?",
            choices: [{ value: "1", text: "Female" }, { value: "2", text: "Male" }],
            showOtherItem: true, otherText: "Prefer to self-describe (please specify)", isRequired: true,
          },
          { type: "dropdown", name: "home_country", title: "What is your home country?", choices: COUNTRIES, isRequired: true },
        ],
      },

      /* ---- countries lived > 3 months ------------------------------------ */
      {
        name: "countries_lived",
        elements: [
          {
            type: "paneldynamic", name: "countries_lived",
            title: "Besides your home country, have you lived in any other countries for more than 3 months? If so, add each one below (you can leave this empty if not).",
            templateElements: [
              { type: "dropdown", name: "country", title: "Country", choices: COUNTRIES, isRequired: true },
              { type: "text", name: "duration_months", title: "Approximately how many months did you live there?", inputType: "number", min: 0, max: 1200, isRequired: true },
            ],
            panelCount: 0, panelAddText: "Add a country", panelRemoveText: "Remove",
          },
        ],
      },

      /* ---- education + occupation ---------------------------------------- */
      {
        name: "education",
        elements: [
          {
            type: "radiogroup", name: "education", title: "Highest or current level of education:",
            choices: [
              { value: "1", text: "Less than high school" },
              { value: "2", text: "High school / GED" },
              { value: "3", text: "Professional / vocational training" },
              { value: "4", text: "Some college (no degree)" },
              { value: "5", text: "Associate's degree" },
              { value: "6", text: "Bachelor's degree" },
              { value: "7", text: "Some graduate school" },
              { value: "8", text: "Master's degree" },
              { value: "9", text: "Doctorate or equivalent (PhD, MD, JD)" },
            ],
            showOtherItem: true, otherText: "Other (please specify)", isRequired: true,
          },
          { type: "text", name: "years_education", title: "How many years of formal education do you have in total?", inputType: "number", min: 0, max: 40, isRequired: true },
          {
            type: "dropdown", name: "occupation", title: "What is your occupation?",
            choices: [
              "Student", "Education / Teaching", "Healthcare / Medicine", "Engineering / IT / Software",
              "Science / Research", "Business / Finance / Management", "Law / Legal", "Arts / Media / Design",
              "Sales / Retail", "Service / Hospitality", "Administration / Office / Clerical",
              "Skilled trades / Construction", "Government / Public sector", "Self-employed / Entrepreneur",
              "Homemaker", "Unemployed", "Retired",
            ],
            showOtherItem: true, otherText: "Other (please specify)", isRequired: true,
          },
        ],
      },

      /* ---- English -------------------------------------------------------- */
      {
        name: "english_native",
        elements: [yesno("english_native", "Do you consider yourself a native speaker of English?", {
          choices: [{ value: "1", text: "Yes" }, { value: "2", text: "No" }],
        })],
      },
      {
        name: "english_profile",
        elements: [
          note("english_profile_h", "Please tell us about your English."),

          prof("prof_speaking_en", "Proficiency in English — Speaking"),
          ctx("speaking_contexts_en", "I can speak English… (select all that apply)", [
            "To communicate while traveling abroad",
            "With friends and family",
            "To ask a question in class",
            "To give a lecture or presentation to an audience",
            "In a job interview or at work",
            "In everyday casual conversation",
          ]),

          prof("prof_understanding_en", "Proficiency in English — Understanding spoken language"),
          ctx("understanding_contexts_en", "I can understand spoken English… (select all that apply)", [
            "In everyday conversations",
            "When watching films/TV without subtitles",
            "When following a lecture or presentation",
            "When the speaker talks fast or has a strong accent",
            "When listening to the news, radio, or podcasts",
          ]),

          prof("prof_reading_en", "Proficiency in English — Reading"),
          ctx("reading_contexts_en", "I can read English… (select all that apply)", [
            "Everyday texts (signs, menus, messages)",
            "News articles and magazines",
            "Novels and other fiction",
            "Academic or technical texts",
            "Official documents or contracts",
          ]),

          prof("prof_writing_en", "Proficiency in English — Writing"),
          ctx("writing_contexts_en", "I can write English… (select all that apply)", [
            "Everyday messages (texts, emails to friends)",
            "Formal emails or letters",
            "Essays or reports",
            "Academic or professional documents",
            "Filling out forms",
          ]),

          age("age_start_en", "At what age did you start learning English? (put 0 for from birth)"),
          age("age_fluent_en", "At what age did you become fluent in English?"),
          age("age_read_en", "At what age did you begin reading in English?"),
          age("age_read_fluent_en", "At what age did you become a fluent reader in English?"),
          yesno("read_to_child_en", "As a child, were you read to aloud in English?"),
        ],
      },

      /* ---- weekly habits: reading / listening / speaking / writing ------- */
      habitsPage("reading", "reading each type of material in English", [
        "Books and printed materials",
        "Emails",
        "Documents (PDFs, Word, etc.)",
        "Websites (News, blogs, searches, etc.)",
        "Social media",
        "Text messages",
        "TV or video subtitles",
        "Other",
      ]),
      habitsPage("listening", "listening to English in each context", [
        "Conversations in person",
        "Phone or video calls",
        "TV, films, or videos",
        "Music with English lyrics",
        "Podcasts or radio",
        "Lectures or lessons",
        "Audiobooks",
        "Everyday interactions (shops, services)",
        "Other",
      ]),
      habitsPage("speaking", "speaking English in each context", [
        "Conversations with friends and family",
        "At work or school",
        "Phone or video calls",
        "Presentations or lectures",
        "Everyday interactions (shops, services)",
        "Other",
      ]),
      habitsPage("writing", "writing in English in each context", [
        "Text messages or chat",
        "Emails",
        "Social media posts or comments",
        "Documents, essays, or reports",
        "Notes for yourself",
        "Forms",
        "Creative writing (stories, poems, etc.)",
        "Journaling or diary entries",
        "Other",
      ]),

      /* ---- other languages ----------------------------------------------- */
      {
        name: "other_languages",
        elements: [yesno("other_languages", "Do you speak or know any languages other than English?", {
          choices: [{ value: "1", text: "Yes" }, { value: "2", text: "No" }],
        })],
      },
      {
        name: "other_languages_panel",
        visibleIf: "{other_languages} = '1'",
        elements: [
          {
            type: "paneldynamic", name: "other_languages_panel",
            title: "Please add each other language you know and answer the questions for it.",
            templateTitle: "Language: {panel.lang_name}",
            panelCount: 1, minPanelCount: 1,
            panelAddText: "Add another language", panelRemoveText: "Remove this language",
            // each added language must be unique (no choosing the same one twice)
            keyName: "lang_name",
            keyDuplicationError: "You've already added this language — please pick a different one.",
            templateElements: [
              // English is handled separately, so it's excluded from the list here
              { type: "dropdown", name: "lang_name", title: "Which language?", choices: LANGS.filter((l) => l.value !== "English"), isRequired: true },
              ...languageQuestions(""),
            ],
          },
        ],
      },

      /* ---- ranking + percentages across all languages -------------------- */
      {
        name: "language_summary",
        visibleIf: "{other_languages} = '1'",
        elements: [
          note("language_summary_h", "Now think about <strong>all</strong> the languages you know (English and the ones you listed)."),
          { type: "ranking", name: "lang_dominance", title: "Order the languages by how DOMINANT they are for you (drag the most dominant to the top).", choices: [], isRequired: true },
          { type: "ranking", name: "lang_acquisition", title: "Order the languages by ORDER OF ACQUISITION (the language you acquired first at the top).", choices: [], isRequired: true },
          { type: "matrixdropdown", name: "lang_exposure_pct", title: "On average, what percentage of the time are you currently exposed to each language? (should total 100%)", rows: [], columns: [{ name: "pct", title: "% of time", cellType: "slider", min: 0, max: 100, step: 1, isRequired: true }] },
          { type: "matrixdropdown", name: "lang_speak_pct", title: "If you could choose, what percentage of the time would you speak each language with someone equally fluent in all of them? (should total 100%)", rows: [], columns: [{ name: "pct", title: "% of time", cellType: "slider", min: 0, max: 100, step: 1, isRequired: true }] },
          { type: "matrixdropdown", name: "lang_read_pct", title: "If a text were available in all your languages, in what percentage of cases would you choose to read it in each? (should total 100%)", rows: [], columns: [{ name: "pct", title: "% of cases", cellType: "slider", min: 0, max: 100, step: 1, isRequired: true }] },
        ],
      },

      /* ---- vision -------------------------------------------------------- */
      {
        name: "vision",
        elements: [
          {
            type: "tagbox", name: "vision_problem",
            title: "Do you have any of the following vision conditions? (select all that apply)",
            choices: [
              "Myopia (Nearsightedness)",
              "Hyperopia (Farsightedness)",
              "Astigmatism",
              "Amblyopia (Lazy Eye)",
              "Dry Eyes",
              "Cataracts",
              "Color Blind",
            ],
            showNoneItem: true, noneText: "None",
            showOtherItem: true, otherText: "Other (please specify)", isRequired: true,
          },
        ],
      },

      /* ---- hearing status (gates the Deaf/ASL battery) ------------------- */
      {
        name: "hearing_status",
        elements: [
          { type: "radiogroup", name: "hearing_status", title: "Please select your hearing status:", choices: [{ value: "hearing", text: "Hearing" }, { value: "deaf_hoh", text: "Deaf or hard-of-hearing" }], isRequired: true },
          yesno("native_sign", "Is a sign language (e.g., ASL) one of your native or home languages?"),
        ],
      },

      /* ===================== Deaf / ASL battery (RAD) ===================== */
      {
        name: "deaf_1", visibleIf: DEAF,
        elements: [
          info("deaf_1_h", "The next questions are about your hearing and sign-language background."),
          yesno("know_asl", "Do you know ASL?"),
          age("age_became_deaf", "At what age did you become deaf? (put 0 for at birth)"),
          { type: "text", name: "db_level", title: 'What is your dB level? (write "unknown" if unknown). Respond in the order R, L.', isRequired: true },
          { type: "radiogroup", name: "deafness_classification", title: "How would you classify your deafness?", choices: ["Mild", "Moderate", "Severe", "Profound"], isRequired: true },
        ],
      },
      {
        name: "deaf_2_aids", visibleIf: DEAF,
        elements: [
          { type: "radiogroup", name: "used_hearing_aids", title: "Have you ever used hearing aids?", choices: ["Never", "Yes, currently", "Yes, in the past"], isRequired: true },
          { type: "matrix", name: "hearing_aid_usage", title: "Please estimate how much you use(d) your hearing aids in these settings:", visibleIf: AIDS_USED, columns: USAGE_COLS, rows: SETTING_ROWS, isAllRowRequired: true },
          age("hearing_aid_start_age", "At what age did you start using hearing aids?", { visibleIf: AIDS_USED }),
          age("hearing_aid_stop_age", "At what age did you stop using hearing aids? (leave 0 if still using)", { visibleIf: "{used_hearing_aids} = 'Yes, in the past'" }),
        ],
      },
      {
        name: "deaf_3_ci", visibleIf: DEAF,
        elements: [
          { type: "radiogroup", name: "cochlear_implant", title: "Do you have a cochlear implant?", choices: ["No", "Yes but I do not currently use it", "Yes and I currently use it"], isRequired: true },
          { type: "text", name: "ci_age", title: "At what age did you receive your cochlear implant? If you have two, list the ages in order R, L.", visibleIf: CI_YES, isRequired: true },
          { type: "matrix", name: "ci_usage", title: "Please estimate how much you use(d) your cochlear implant in these settings:", visibleIf: CI_YES, columns: USAGE_COLS, rows: SETTING_ROWS, isAllRowRequired: true },
          { type: "radiogroup", name: "device_function", title: "When you use(d) your hearing devices, what was their primary function?", visibleIf: "(" + CI_YES + ") or (" + AIDS_USED + ")", choices: ["Language and speech", "Environmental sounds", "Both"], isRequired: true },
          { type: "comment", name: "device_describe", title: "If you would like, describe how you use(d) your hearing device (optional).", isRequired: false },
        ],
      },
      {
        name: "deaf_4_asl", visibleIf: DEAF,
        elements: [
          yesno("asl_exposure_early", "Were you exposed to ASL from early childhood?"),
          age("age_exposed_asl", "At what age were you exposed to ASL? (put 0 for from birth)"),
          yesno("primary_parent_deaf", "Is your primary parent or guardian deaf?"),
          { type: "radiogroup", name: "secondary_parent_deaf", title: "Is your secondary parent or guardian deaf?", choices: ["Yes", "No", "NA"], isRequired: true },
          { type: "checkbox", name: "learned_asl_from", title: "From whom did you learn ASL in early childhood?", choices: ["Parents/guardians", "Siblings", "Extended family members", "Friends", "Others"], isRequired: false },
        ],
      },
      {
        name: "deaf_5_home", visibleIf: DEAF,
        elements: [
          { type: "radiogroup", name: "home_language_primary", title: "What language did you primarily use at home with parents and family?", choices: ["ASL/PSE/SEE", "Spoken English", "Other nationally recognized sign language", "Other spoken language"], isRequired: true },
          { type: "checkbox", name: "home_language_other", title: "Please select other languages used at home and with family.", choices: ["ASL/PSE/SEE", "Spoken English", "Other nationally recognized sign language", "Other spoken language", "No other languages used at home"], isRequired: false },
          yesno("deaf_siblings", "Do you have any deaf siblings?"),
          yesno("sibling_knows_asl", "Does your sibling know ASL?", { visibleIf: "{deaf_siblings} = 'yes'" }),
          yesno("older_deaf_siblings", "Do you have any OLDER deaf siblings?", { visibleIf: "{deaf_siblings} = 'yes'" }),
          yesno("younger_deaf_siblings", "Do you have any YOUNGER deaf siblings?", { visibleIf: "{deaf_siblings} = 'yes'" }),
        ],
      },
      {
        name: "deaf_6_edu", visibleIf: DEAF,
        elements: [
          {
            type: "matrix", name: "education_modality", title: "Please select the modality you used during each educational period.",
            columns: ["Daycare/preschool", "Elementary School", "Middle School", "High School", "College"].map((t) => ({ value: t, text: t })),
            rows: ["ASL only", "Spoken English only", "Mix of ASL and spoken English", "Other sign language only", "Other spoken language only"].map((t) => ({ value: t, text: t })),
          },
          { type: "text", name: "years_studied_english", title: "How many years did you formally study English?", inputType: "number", min: 0, max: 80, isRequired: true },
          { type: "text", name: "years_studied_asl", title: "How many years did you formally study ASL?", inputType: "number", min: 0, max: 80, isRequired: true },
          { type: "text", name: "years_used_english", title: "How many total years have you used English?", inputType: "number", min: 0, max: 120, isRequired: true },
          { type: "text", name: "years_used_asl", title: "How many total years have you used ASL?", inputType: "number", min: 0, max: 120, isRequired: true },
        ],
      },
      {
        name: "deaf_7_aslprof", visibleIf: DEAF,
        elements: [
          {
            type: "matrix", name: "asl_proficiency", title: "Please rate your proficiency for ASL.",
            columns: ["Almost none", "Very poor", "Fair", "Functional", "Good", "Very Good", "Like Native"].map((t) => ({ value: t, text: t })),
            rows: ["Signing", "Understanding"].map((t) => ({ value: t, text: t })),
            isAllRowRequired: true,
          },
          { type: "comment", name: "language_history_note", title: "Is there anything you would like to add about your language history? (optional)", isRequired: false },
        ],
      },

      /* ---- learning / reading disability + handedness -------------------- */
      {
        name: "language_impairment",
        elements: [
          {
            type: "tagbox", name: "language_impairment",
            title: "Do you have any neurological disorders, learning disorders, or reading disabilities? (select all that apply)",
            choices: [
              "Dyslexia",
              "Dysgraphia",
              "Dyscalculia",
              "Specific Language Impairment (SLI)",
              "Stuttering",
              "ADHD",
              "Autism Spectrum Disorder",
              "Epilepsy",
              "Aphasia",
            ],
            showNoneItem: true, noneText: "None of the above",
            showOtherItem: true, otherText: "Other (please specify)", isRequired: true,
          },
          // follow-ups, shown only when a disorder (not "None") is selected
          age("impairment_age", "At what age were you (first) diagnosed?", {
            visibleIf: "{language_impairment} notempty and {language_impairment} notcontains 'none'",
          }),
          {
            type: "comment", name: "impairment_specify",
            title: "Please tell us a bit more about your disorder(s).",
            visibleIf: "{language_impairment} notempty and {language_impairment} notcontains 'none'",
            isRequired: true,
          },
        ],
      },
      {
        name: "dominant_hand",
        elements: [{ type: "radiogroup", name: "dominant_hand", title: "Which hand is your dominant hand?", choices: [{ value: "1", text: "Right" }, { value: "2", text: "Left" }, { value: "3", text: "Both" }], isRequired: true }],
      },
    ],
  };

  /* Populate the ranking choices + percentage matrix rows from the languages
     the participant actually entered (English + each panel language). */
  const survey_function = function (survey) {
    function langs() {
      const out = ["English"];
      const p = survey.getQuestionByName("other_languages_panel");
      if (p && Array.isArray(p.value)) {
        p.value.forEach((v) => { if (v && v.lang_name) out.push(v.lang_name); });
      }
      return out;
    }
    const PCT = ["lang_exposure_pct", "lang_speak_pct", "lang_read_pct"];
    function pctSum(v) {
      let s = 0;
      Object.keys(v || {}).forEach((k) => { const c = v[k]; if (c && c.pct !== "" && c.pct != null) s += Number(c.pct); });
      return s;
    }
    function showTotal(name) {
      const q = survey.getQuestionByName(name); if (!q) return;
      const sum = pctSum(q.value);
      q.description = sum === 100 ? "✓ Adds up to 100%" : "Running total: " + sum + "% — should add up to 100%";
    }
    function populate() {
      const L = langs();
      const items = L.map((l) => ({ value: l, text: l }));
      ["lang_dominance", "lang_acquisition"].forEach((n) => {
        const q = survey.getQuestionByName(n); if (q) q.choices = items;
      });
      PCT.forEach((n) => {
        const q = survey.getQuestionByName(n); if (q) q.rows = items;
        showTotal(n);
      });
    }
    survey.onCurrentPageChanging.add(function (s, opt) {
      if (opt.newCurrentPage && opt.newCurrentPage.name === "language_summary") populate();
    });
    survey.onValueChanged.add(function (s, opt) {
      if (PCT.indexOf(opt.name) !== -1) showTotal(opt.name);
    });
    populate();

    // Hard-enforce that each percentage matrix sums to exactly 100%.
    survey.onValidateQuestion.add(function (s, opt) {
      if (["lang_exposure_pct", "lang_speak_pct", "lang_read_pct"].indexOf(opt.name) === -1) return;
      const val = opt.value || {};
      let sum = 0, n = 0;
      Object.keys(val).forEach(function (k) {
        const cell = val[k];
        if (cell && cell.pct !== undefined && cell.pct !== "") { sum += Number(cell.pct); n++; }
      });
      if (n > 0 && sum !== 100) {
        opt.error = "Your percentages must add up to 100% (they currently add up to " + sum + "%).";
      }
    });
  };

  return [IVQ.makeSurvey(survey_json, { part: "part1" }, survey_function)];
};
